server:
  port: 8080

spring:
  application:
    name: auth-service
  datasource:
    url: ${DATA_URL}
    username: ${DATA_USER}
    password: ${DATA_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${YOUR_GOOGLE_CLIENT_ID}
            client-secret: ${YOUR_GOOGLE_CLIENT_SECRET}
            scope: profile, email
          github:
            client-id: ${YOUR_GITHUB_CLIENT_ID}
            client-secret: ${YOUR_GITHUB_CLIENT_SECRET}
            scope: read:user,user:email
  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration

jwt:
  secret: ${your_jwt_secret_key}
  expiration: 3600000
  refresh-expiration: 604800000

bcrypt:
  strength: ${BCRYPT_STRENGTH:12}

logging:
  level:
    root: INFO
    my.code.auth: INFO
